format: json
output: circlelist.json
event:
  comitia134:
    circle_list_url: https://www.comitia.co.jp/history/134list_sp.html
    parser: Comitia134Parser
  comitia136:
    circle_list_url: https://www.comitia.co.jp/history/136list_sp.html
    parser: Comitia134Parser

