name: release 

on:
  push:
    # tags:
    #   - 'V*'

jobs:
  release:
    name: Release on Github
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - name: Build for linux
        run: go build . -o go-circle-list-extract_linux-amd64
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Build for Windows
        run: go build . -o go-circle-list-extract_win-amd64.exe
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Build for darwin
        run: go build . -o go-circle-list-extract_darwin-amd64
        env:
          GOOS: darwin
          GOARCH: amd64
      - run: ls -alt