name: release 

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release on Github
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - name: Test
        run: make test
      - name: go mod verify
        run: make verify
      - name: Build for linux
        run: go build -o ./go-circle-list-extract-linux-amd64 .
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Build for Windows
        run: go build -o ./go-circle-list-extract-windows-amd64.exe .
        env:
          GOOS: windows
          GOARCH: amd64
      - name: Build for darwin
        run: go build -o ./go-circle-list-extract-darwin-amd64 .
        env:
          GOOS: darwin
          GOARCH: amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            go-circle-list-extract*
            config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}