name: release 

on:
  push:
    # tags:
    #   - 'V*'

jobs:
  release:
    name: Release on Github
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - run: go build .
      - run: ./go-circle-list-extract -h